[app]

# (str) Title of your application
title = Fleet Management System 2600

# (str) Package name
package.name = fleetapp2600

# (str) Package domain (needed for android packaging)
package.domain = org.jamal.fleet

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (file extensions)
source.include_exts = py,png,jpg,kv,atlas,json,yml,yaml,txt,db,mp3,wav

# (list) List of inclusions 
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (file extensions)
source.exclude_exts = spec

# (list) List of directory to exclude
source.exclude_dirs = tests, bin, .venv, .git, .github

# (list) List of exclusions
#source.exclude_patterns = license/autogenerated/*,*/__pycache__/*

# (str) Application versioning
version = 1.0.0

# (list) Application requirements
requirements = python3,kivy,kivymd,requests,urllib3,certifi,chardet,idna

# (list) Garden modules to install
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = Name:service.py

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for android toolchain)
android.presplash_color = #1A0000

# (list) Permissions
android.permissions = INTERNET,RECORD_AUDIO,CAMERA,READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE,ACCESS_FINE_LOCATION,ACCESS_COARSE_LOCATION

# (int) Target Android API, should be as high as possible.
android.api = 33

# (int) Minimum API required
android.minapi = 21

# (int) Android SDK version to use
#android.sdk = 33

# (str) Android NDK version to use
android.ndk = 25b

# (bool) Use --limit-modules if specified when creating the bundle
#android.limit_modules = 0

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip python export when building the APK
#android.skip_update = False

# (bool) If True, then accept all SDK licenses automatically
android.accept_sdk_license = True

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.kivy.android.PythonActivity

# (list) List of Java .jar files to add to the libs
#android.add_jars = foo.jar,bar.jar,src/bar.jar

# (list) List of Java files to add to the project (will be compiled)
#android.add_src =

# (list) Android AAR archives to add
#android.add_aars =

# (list) Gradle dependencies to add
#android.gradle_dependencies =

# (bool) Enable AndroidX support
android.enable_androidx = True

# (list) External Java libraries to add
#android.add_javaclass =

# (str) The Android architectures to build for
android.archs = arm64-v8a

# (bool) Allow backup of application data
android.allow_backup = True

# (str) The format used to package the app for release mode (aab or apk or aar)
android.release_artifact = apk

# (str) The format used to package the app for debug mode (apk or aar)
android.debug_artifact = apk


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug)
log_level = 2

# (int) Display warning if buildozer is run as root
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output storage, absolute or relative to spec file
# bin_dir = ./bin
